### ISSUE TITLE
Signal strings within an action chain to increase modularity

### ISSUE THREAD

**Issue by aultac** [cerebral/cerebral#142] opened 2015-12-23 03:52 UTC
I've seen several places that @christianalfoni has mentioned a desire to avoid calling signals from within action functions because it makes the program harder to follow.  One of the things I like about signals is that they help to de-couple components from each other in a very specific way: rather than have to require a particular component to exist, you can just put a signal string there like "somebody has to deal with this" and the controller handles doling out the responsibilities.

Since a signal is really just a named chain of actions, I've come across instances on a reasonably complex project where I've found myself embedding a signal within another action chain because there was no good reason to repeat the actual chain of actions again outside the signal definition.  I made an action factory for it:

```javascript
    Cerebral.signal('seatmap.purchaseableClicked', [
      actions.isPurchaseableAvailable,
      {
        yes: [
          actions.transformPurchaseableToCartItem,
          // The returned function below just calls Cerebral.signal.cart['toggle-item'](input)
          factories.signal(Cerebral, 'cart.toggle-item'), 
        ],
        no: [
          factories.log('Clicked on an unavailable seat'),
        ],
      }
    ]);
```

In that case, I just want to run the `cart.toggle-item` chain of actions as-is, with the previous input from the chain, without repeating the actual code specifying the chain.

I'd like to see what the consensus is around this situation.  It seems there are two reasonable options that avoid needing to signal things from within an action function itself as I have above (which I agree could make program flow harder to follow in general cases)

1. Allow a signal to be triggered by it's string name within an action chain.
```javascript
Cerebral.signal('seatmap.purchaseableClicked', [
  actions.isPurchaseableAvailable,
  {
    yes: [
      actions.transformPurchaseableToCartItem,
      'cart.toggle-item', // Replace the action itself with a signal string for Cerebral to interpret
    ],
    no: [
      factories.log('Clicked on an unavailable seat'),
    ],
  }
]);
```

2. Force the `cart` component above to group each signal's entire chain into a single action chain variable, and import that particular component within all other things that need to use that signal:

```javascript
import { chains as CartChains } from '../cart';
Cerebral.signal('seatmap.purchaseableClicked', [
  actions.isPurchaseableAvailable,
  {
    yes: [
      actions.transformPurchaseableToCartItem,
      ...CartChains.toggleItem, // expand the chain of actions for that signal in place
    ],
    no: [
      factories.log('Clicked on an unavailable seat'),
    ],
  }
]);
```

The problem I see with Option 2 (which is what I understand to be the recommended approach to this) is that if I move the cart component around, or want to swap out another cart component in a different project, the import will break.  It also relies heavily on everyone coding in the project always faithfully representing all signals as exactly one chain variable in case of reuse outside the component.  

Option 1 (allow Cerebral to recognize strings in the action chain as signals) seems to be a much cleaner, more reliable solution.  It just says "in order for this component to work in whatever environment it's placed, somebody has to implement the 'cart.toggle-item' signal".  

Thoughts?

**Comment by abalmos** [comment] 2015-12-27 23:56
After discussing with @garth and @Guria on gitter I think the best way to handle this is to move "cart.toggle-item" to a service that the cart module exposes. Particularly if services can access the controller as suggested at the end of #129.

**Comment by christianalfoni** [comment] 2015-12-28 14:54
Really great writeup @aultac !

Yeah, as you state the recommended way is `...CartChains.toggleItem`. I see your point allowing strings there and we could do that as long as the string is used to extract the actual chain from that signal. So everything is composed into one signal running.

We want it to run as one signal or you could fire off signals all over the place and they would not be able to wait for each other etc. If their chains are composed into one signal you can wait for one signal to finish before running the next etc. So yeah, that is doable. But there are two problems:

1. With a string the referenced signal has to exist when analyzing the signal. This can be confusing. You have to add signals in a specific order

2. It is harder to find the file containing information about that signal. If you imported its chain into the file, as the current convention you know where it comes from. In some IDEs you can even click it and jump into the file

So yeah, my biggest concern is the first point there. You have to register the signal itself before you can use it. But now you just need to import the file containing the chain.

**Comment by aultac** [comment] 2015-12-29 03:35
@abalmos: is the suggestion above to have the cart expose a service that will in turn call the signal to run the chain of actions associated with `cart.toggleItem`?  That doesn't seem to be any different (beyond being more confusing to follow) than just calling the signal from the action directly.  Or is the suggestion to not allow `cart.toggleItem` to be a chain of actions at all, but rather it's own function that modifies the state, and expose that function as a service?  In that case, I'd rather keep all my actual state-changing confined to actions if I can help it, and definitely not have to repeat state-changing code once in actions and once as a service.

@christianalfoni: I don't think it needs to be a requirement that the signal has to exist at the time of registration.  It could either always evaluate the string at call time (as my current implementation clearly does by explicitly calling the signal), or populate it lazily: i.e. if it exists when registered, fine.  If not, keep the string and try to evaluate it again at some later time, either on the first call to the outer signal, or during the registration of any subsequent signals.  In the latter case, you'd still get to analyze all the signals at registration time, it's just that a signal containing strings in it's action chain may not be considered invalid until it's called and it's discovered that nobody ever registered that one.  It will still be quite an obvious error at that point: used a signal string that didn't exist in a particular action chain.  I believe this is currently how Cerebral handles things when one calls an unknown signal, so nothing different there.

As for being harder to find the file containing the signal, I don't think `grep -r 'cart.toggleItem' *` (or `ag cart.toggleItem`) is too bad :).  Part of the point is that the standard method of explicitly requiring paths makes it much less modular and reusable, so definitionally anything that replaces the explicit path with a more dependency-injection-like pattern will have that issue.  You could claim the same thing about signals themselves: why have the strings at all?  Why not just require the action chains directly wherever you need to use them?  I see the real power of the string name being modularity: the caller of the signal doesn't have to know anything about who registered it.

**Comment by christianalfoni** [comment] 2016-01-02 16:11
@aultac Yeah, it is not a requirement, but it increases the complexity how Cerebral works internally. Increasing complexity is often an indicator that it might not be a good idea to do it :-) That said, I just have to put skepticism into all ideas, just to make sure we do overlook a scenario etc.

You make a good point on "why even define signals at all", you could just point to the chain really. It is nice to be able to reuse the signal definition for easier compose ability.

The analysis will actually still work allowing strings for reference. Because the analysis of the signal referencing the other will just skip the string, continuing to the signal referenced later where it might cause an error, because of wrong outputs or whatever. So yeah, strings should just be skipped in the analysis as what is being referenced will be analysed at some point.

When the static tree is being built though, which is done at runtime of signal, that is where the string is converted into an actual chain. Extending the signal.

I think this will work. So as a summary and **suggestion**:

```js

const chain = [
  someAction,
  'someOtherSignal'
]
```

At runtime of signal the string is replaced by the chain of the specified signal. Pointing to non existing signal will give an error.

**Comment by abalmos** [comment] 2016-01-04 18:14
@christianalfoni I like this. From the perspective of the debugger there is only one signal fired, yet the developer is still able to easily compose chains without hard references to specific implementations. It should probably be used sparingly.

Full disclosure: @aultac and I work together and we both wanted it from the get go. We still might want some more outside :+1:'s

I can try to make a PR for this over the next few weeks, unless someone gets to it before me or we kill the idea in the meantime :smile:

**Comment by bfitch** [comment] 2016-01-05 15:17
Hey guys, really interesting discussion. My understanding is that we want to trigger a signal by name within an action chain so we can:
  1.  avoid re-typing the action chain or re-`import`ing it when using it in multiple signals
  2. avoid hardcoded import paths when importing shared chains

Is that a good summary?

IMO, the first point introduces some complexity to save typing or boilerplate. I can appreciate the elegance of the solution, but I favor keeping the API and abstractions smaller if the motivating factor is mainly saving keystrokes. To the second point, is the use case when you move a file exporting the chain in your project tree? I definitely know the pain of renaming and changing paths in a large refactor. But, in this case I wonder how many files will actually share these chains? Like 5,10, or 50? If it's the former, not sure if it's worth introducing more API. At least it's not worth it to me :stuck_out_tongue: 

That said, I'm not completely opposed to the change! I'll let @christianalfoni weigh in on how much complexity it would add to the implementation. But, it will expand the API and introduce another concept to cerebral, which we should consider carefully.

**Comment by maxfrigge** [comment] 2016-01-05 18:05
I agree with @bfitch that those features should not be added willy-nilly. I think the use case of combining signals has a lot of potential, but it should be thought about very carefully. Maybe it's better to add the case to some sort of wish list and taken into account when the time has come for an action/signal refactoring?

**Comment by Guria** [comment] 2016-01-05 18:12
+1 for @bfitch.

**Comment by tnrich** [comment] 2016-01-05 19:32
I'm also skeptical of the new syntax. It seems like it's just one more thing to learn. That said it does look pretty clean :)

**Comment by christianalfoni** [comment] 2016-01-06 07:51
There is also the fact that it looks rather weird that:

```js
[
  someAction,
  'home.buttonClicked'
]
```

That is of course more of a naming convention, but it affects the reasoning of the app.

And there is also a matter of that signal is bound by the router. Should the router update? Or should it not?

I agree we should wait a bit, at least until modules are ready. Aa that also affects how we reason about all this :-)

**Comment by aultac** [comment] 2016-01-09 03:36
Thanks for the feedback, everybody.  I've been thinking on this quite a bit lately because the problem with the example I showed above is the signal name is a present-tense verb (`cart.toggle-item`).  This was bugging me because conceptually the signals really should be past-tense verbs (i.e. `cart.item-toggled`).  So I was trying to figure out if I was simply thinking of the problem wrong.  The only reason this is coming up at all is because I only want to code with modules that are each in charge of particular parts of the state.

I decided that for now option #2 from my original post (force all signals to reference a single exported chain) might be the best solution if I really think the signal's name should be a present-tense verb.  I'm just about finished with a major refactor of my app which took that approach, and it's finally become clear to me the right way to think about this and why I think it's still worth discussing here for formal support within Cerebral.  @bfitch, @maxfrigge, @Guria: what do you guys think of this train of thought:

A signal should represent something that just happened, and whoever cares about that thing happening can then deal with it's occurence.  i.e. a signal represents a reportable event.  As currently conceived where you'd prefer not to allow signals to emanate from action chains, what's you're really saying as an architectural constraint on a Cerebral app is that reportable things can't "happen" in actions.  Sort of "you should structure your entire app around action chains, but nothing important enough to report about can happen there."

But there are in fact many cases where reportable things happen in actions once you've modularized your code.  In fact, it would seem that since an 'action' is a present-tense verb, then conceptually the completion of each action is potentially a signal (although I don't think I would use things in that way myself).  

Here is an example I have at the moment that I think is somewhat common: one object that's controlled by `module1` that refers to another object that is managed by `module2`.  Something like this in the state tree:

```javascript
var tree = {
  questid: 1,    // current id of the quest we're on
  questorid: 2, // id of the person we're currently looking at, who is on a quest
  quests: {
    1: { name: 'The Holy Grail' },
  },
  questors: {
    2: { name: 'Lancelot', questid: 1 },
  },
}
```

Whenever someone navigates to the page `/questors/2`, a signal is emitted indicating there is a new questor to look at.  This signal is handled by the `questors` module, and it runs an action chain that takes the questorid from the URL, sets it as the current questor in the state, and fires a REST request to refresh the info for questor 3.  

Now, since Lancelot is currently on the quest for The Holy Grail, clearly we need to handle updating  the information about the quest while we are handling the changeover to Lancelot as the current questor.  The trouble is, the `questors` module shouldn't be messing with quests, because quests are managed by the `quests` module.  If only there was some conceptual way for the `questors` module to let the `quests` module know that there is a new questid in town and it should refresh it's local copy.  Note this refresh could occur from the action's input chain if both the quest and questor are returned in the same REST response, or it could trigger a new REST request for the quest information once it has the new questid after loading Lancelot's information. 

To my mind, it seems the right way to think about this problem is that the `questor` module should fire off a signal like `quests.theres-a-new-questid-in-town`, and the `quests` module would then execute the action chain that deals with making sure that questid exists locally in the state.  That way you know in your application that only a particular module contains code to handle a particular part of the state, and you avoid the slippery slope of exporting actions and chains from a module to rest of your app that may end up changing parts of the state tree in inconsistent ways.

I agree with @christianalfoni that lots of asynchronous signals firing off unpredictably is undesirable because it would make it harder to track down execution flow in the debugger.  However, as @abalmos pointed out, simply thinking of the signal as a placeholder for the action chain makes it very easy to follow what's happening.  It also makes the app much more testable because you can test the signal itself, and then re-use that signal around the app.

**Comment by christianalfoni** [comment] 2016-01-12 16:57
Thanks for taking the time to explain this in detail @aultac :-)

One question, `quests.theres-a-new-questid-in-town`, is there any other way this signal can trigger from the outside? Other than from an other signal? If not it kinda goes against the point of a signal, which is "the outside to request change on the inside".

I acknowledge the reasoning around off putting work from one module to an other, but that is a bit counter intuitive to what Cerebral tries to do. With Cerebral you just "do the work requested". So when a signal fires you run all the logic needed to make the necessary changes... regardless of what module owns the signal.

Modules are not very rigid, they basically just namespace your signals, state and services. Nothing more. They do not say. "This module should only handle everything related to this domain". I think that is utopia, and you will refactor yourself to bankruptcy if you try to build "the perfect separation of concerns" ;-) 

An example of this is the TodoMVC demo. The "new" module is responsible for adding a new todo as you type the name in the form and hit enter. But the list of todos exists in the "list" module. So this would be the same issue as you describe, should "new" module off put the work to "list"?

My answer to this is: "no". "new" just points to "list" module state and adds a new todo to it. Modules are a happy family, not living alone on islands :)

But I am not saying I am right here, it is a very fundamental question and very difficult to answer. I am not against trying this out, we can implement it and set it as experimental :) But would a couple thumbs up from a couple of other devs before doing it

**Comment by fricke** [comment] 2016-01-26 09:45
My response on the proposed solution to use strings, like 'app.module2.signal', seems 
a little strange, but could be powerful for complex situations like the one I’m about to describe.  
However, it also may not read well and cannot be verified if it's available until 
runtime of the signal chain.  Maybe that's fine, but it does have that drawback, but 
with the advantage of being very short syntax.  

I wanted to first sort of go through how I’m currently building things to show the pain points in more detail for others to understand.  
 
With a lot of great help from the cerebral team on discord (very much thankful for all the help), the solution now for intermodule communication has been to use factories.  Factories can provide contextual information for where to get the data and you can have your signals pass these paths around and know where the context of the action should be run.  This works, of course, but then it seems like I’m needing to build a lot of factories and pass a lot of paths around.  These factories I can’t assign to module.signals because the signals need to be created at runtime (I have a factories.js file in most of my modules that are factory => signal chains).  I’m using a lot of factories because I’m trying to make most modules very reusable... a hard requirement for the application I’m working on.  Further, these paths have to come from the top of where they are defined, mainly in the module’s setup file, requiring that my signals are wrapped in a big factory to pass those paths down.  

Next...  I really want to be able to use the module param that is passed through to the action.  It seems very powerful to give your actions contextual module awareness.  As things stand, if you are reusing your module you need to use names or paths to even get it's own current module via modules.  This is what sort of surprised me about reusing these modules and was unexpected behavior.  It makes sense if you just realize that you are importing an external factory or signal chain and using it the current module's context.  

So, on to the basic pattern I'm currently using for my application architecture:

```
// page1/index.js
// module init

import signals from './signals';
export default function(options = {}) {
    return (module, controller) => {
        module.modules({
            module2: Module2(),
            module3: Module3()
        });
        module.signals(signals({
            module2Path: ['app', 'module2'],
            module3Path: ['app', 'module3']
        }));
    }
}

// page1/signals.js
// top level 'composing module's signals, like a page'
// NOTE: all signals are coming from one file

import {
    action1,
    action2
} from './actions';
import {
    doSomethingToModule2
} from '../Module2/factories';

import {
    doSomethingToModule3
} from '../Module3/factories';

export default ({ module2Path, module3Path }) => {
    return {
        awesomeChain: [
            doAction,
            doSomethingToModule2(module2Path),
            doSomethingToModule3(module3Path)
        ]
    };
}

// module2 factories.js
// can't really do anything w/ this file on initializing the module,
// module.signals requires them to be well defined signals.  Would really
// like these to be signals w/o a wrapper factory so we can put them on the module. 

export default {
    return {
        doSomethingToModule2: (dataPath) => {
            return [
		// need to use template strings to get the current module state, would be nice to just do current module syntax
                copy(`state:/${dataPath}`, 'output:/key'),
                // actually need to set state here in the next action, so need a factory
                thisIsGoingToBeTheBestAction(dataPath),  
                maybeThisOneIsJustOkAction,
                // needed dataPath
                wrapItUpAction(dataPath)
            ]
        }
    }
}

// module2 actions.js
export default {
    return {
        thisIsGoingToBeTheBestAction: (dataPath) => {
            return ({ module, modules, state, input }) => {
                // module is actually page1 module. I really can't use it here b/c 
                // as I said before that module could be anything depending on what external 
                // signal chain it's been imported and attached to.  
                // So, we are stuck with needing use state or modules param in combination w/ 'dataPath'

                state.merge(dataPath, {
                    shades: '10DollarShadesIsAllYouNeed'
                });
            }
        },
        // other actions
    }
}

```

There seems to be a lot of passing around contextual information about modules, as 
already mentioned, but now it's even more apparent.  I guess I ask if this is the
unofficial current way of handling intermodule communication?  I imagine it's still being really hashed
out so this is the way it is currently, but can be further developed on.  So I'd like to get my 2 cents in.   

In this proposal, maybe there's a little more code, but it's more initialize time strict to catch errors on load of the page.  

Basically, ff we had access to a module instance in a signal, by passing it down from
module.signals in a factory (still need this great factory pattern) like:

```
// page1/module1
module.modules({
    module2: Module2(),
    module3: Module3()
});

module.signals(signals({
    module2: module.module2,
    module3: module.module3
}));

// module1 signals.js

export default ({ module2, module3 }) {
    return {
        awesomeChain: [
            doAction,
            module2.doSomethingToModule2,
            module3.doSomethingToModule3
        ]
    };
}

```

Calling module2 and module3's signals should then run that method in that 
module "instance" context.  That way in module2's actions, for example, the param 'module'
will be module2, not module1, which again is the opposite in how things are behaving.  This would be huge.  For the most part, your module then can just rely solely on that param to update it's state.  Even the addons would work.   It seems like we wouldn't even be that far off from doing something like this, most of the proposed stuff you can do, it just has the gap of not running a signal as that module and needing to import the factory because you have to pass paths to it.  
 
Now, this is not new and something similar was proposed in
conversation w/ abalmos when hashing through this, but this is slightly different in that you pass
the module “instance” down and not the controller.  Here’s that proposal:

```
import getWeather from '../Weather/factories/getWeather';
import getAlerts from '../Alerts/factories/getAlerts';

export default function(){
    return (module, controller) => {
        module.signals({
        initLoadChart: [
            set('state:./initialLoad', true),
            ...controller.runAsModule(loadName, getLoad),
            ...controller.runAsModule(weatherName, getWeather),
            ...controller.runAsModule(alertName, getAlerts),
            set('state:./initialLoad', false)
        ]
    });
}
```
This is very close and what basically has inspired what I proposed above, just slightly different.  
I don’t want to have to import external logic from a module, it should really be attached.  I’m also weary 
of passing down the controller to signals (I wouldn’t be able to define all my signals in the modules index.js file on 
initialize as shown here).  It also may be a bad pattern for the controller to be used by the signals when the controller is managing those signals.  I have access to the module instance when I define it, so I feel like I should use that and then not have to at a later
time get the module via a path.  Last, you still need to import an external module’s logic outside the context of the module then 
basically “bind” that module chain call when it’s run.  

Again, and I know I'm over stating this need, but I really just want to be able to use the module param.  How things are setup now in my application I can only really use module at the composing signals level.  If i wanted to get the current module I have to get it off modules or just use the state path.  That seems weird.  I like to think of these modules as instances of themselves that carry around all it's state and know how of getting to said state.  

That was a long comment!  Thanks for listening.  Thoughts?

**Comment by fricke** [comment] 2016-01-29 19:10
I just also had maybe another suggestion and it actually expands on the original post here, but less cryptic...

what if we did this

```
controller.trigger('app.loadexplorer', 'initLoad', {
	complete: [],
	error: []
})
```

Then we wouldn't have to pass the module instance in, the path would basically determine the instance of the module.  I threw in the callbacks because it seems like we would want to have the ability to have callbacks.  The other big drawback I'm noticing when using closures/factories to pass in contextual information and create these signals is that I'm using the pattern 

```
        ...getLoad({
            success: [function({ output }){ output(); }],
            error: [function() {} ]
        }),
```

So the chain factory just spreads the handler in the success chains defined.  

```
getLoad: (handlers={}) => {
        let {
            applyDemoOverrides,
            setLoad,
            requestLoad
        } = actionFactory(loadPath);
        loadPath = loadPath.join('.');
        return [
            determineDateRangeRequestRange(loadPath), {
                success: [
                    set(`state:/${loadPath}.loading`, true),
                    determineIfDateRangeDataIsCached(loadPath), {
                        isCached: _.compact([
                            ...handlers.success,
                            set(`state:/${loadPath}.loading`, false)
                        ]),
                        notCached: [[
                            requestLoad, {
                                success: _.compact([
                                    setLoad,
                                    when(`state:/${loadPath}.900.overrides`), {
                                        isTrue: [applyDemoOverrides],
                                        isFalse: []
                                    },
                                    ...handlers.success,
                                    set(`state:/${loadPath}.loading`, false)
                                ])
                            }
                        ]]
                    }
                ]
            }
        ];
    }
```

But then I cannot attach this function to signals because it's not a signal until it's called because of the handlers.  I really would like to be able to have everything attached to the module.  Yeah, I can put it on meta, but it doesn't seem like meta info here.

**Comment by christianalfoni** [comment] 2016-02-21 14:24
I am just closing this for now. We will first implement the `context` suggestion and then we can get back to this discussion :) Just have to prioritize a bit now to push forward

**Closed by christianalfoni** 2016-02-21 14:24 UTC
Labels: question
