### ISSUE TITLE
Finer control to "Memory" storage

### ISSUE THREAD

**Issue by idream3** [cerebral/cerebral#47] opened 2015-08-04 22:58 UTC
We need to ability to choose what signals get remembered, so either I will do this myself or if you feel it is a worthwhile feature we can add it to the API.

```javascript
Controller.signal('somethingHappened', ...actions ).remember(false)
```

The default would be `remember(true)` so you don't have to define it.

The reason is that I am building a history component that is interested in undo/redo for worthwile signals such as add/edit/delete. It is not interested in remembering the state of a text input or other 'minor' signals.

**Comment by christianalfoni** [comment] 2015-08-05 06:23
Hi @idream3 ,

You make a good point here!

But actually I do not think you should undo signals. The reason is that signals does not actually have any notion of what you put into the state store. They just know what the initial arguments are and what actions to run. So this undo functionality should actually be related to the "state" object, a new method.

So:
```js
const action = function (args, state) {
  state.undo(['aPath']);
}
```

So yeah, I think the best solution here is to introduce an "onUndo" hook and do the undoing inside Baobab, or custom for immutable-store. No biggie to implement :-)

Does that make sense?

**Comment by idream3** [comment] 2015-08-05 06:53
Umm, kind of :)

I was basing the signal remembering off the debugger history behaviour. Does it not just remember and replay the signals?

Are you saying that the State store is actually storing the data?

Would it be similar to this with immutable-store?

```javascript
const addItem = function(args, state) {
  // add new item to state array
  state.push('items', args.item);
  // add history label
  state.push('historyState', {
    label: 'Added item: ' + args.item.name),
    state: state.toJS() // export the store
  });
}

// later
const undo = function(args, state) {
  const historyState = state.get(['historyState', args.index]);
  state.import(historyState.toJS());
})
```

Is this close or just way off? :)

**Comment by christianalfoni** [comment] 2015-08-05 07:04
Yeah, so the debugger just knows what signal has been triggered and what argument you gave it. It also remembers the result of async actions. But it does not actually remember the actual state changes, those are reproduced by replaying the signals. Other solutions, like Redux, records the actual state changes... that works too, but then you do not get such a "deep look" into the flow of the app, just what state changes were done.

Using `immutable-store` the `cerebral-react-immutable-store` project needs to add a new hook. So from the source code:

```js
...
var controller = cerebral.Controller({
    defaultArgs: defaultArgs,
    onReset: function () {
      state = initialState;
    },
    onUpdate: function () {
      eventEmitter.emit('change', state);
    },
    onRemember: function () {
      eventEmitter.emit('remember', state);
    },
    onGet: function (path) {
      return Value(path, state);
    },
    onSet: function (path, value) {
      var key = path.pop();
      history[path.join('.')] = Value(path);
      state = Value(path, state).set(key, value);
    },

    onUndo: function (path) {
      var oldValue = history[path.join('.')];
      var key = path.pop();
      state = Value(path, state).set(key, oldValue);
    }
```
I am not sure if this makes too much sense, but the idea is that undo logic has to be part of the `cerebral-react-immutable-store` package. For the baobab package we could probably take advantage of Baobabs internal history handling.

So yeah, two things needs to happen:

1. Cerebral has to expose the `onUndo` hook
2. The `cerebral-react-immutable-store` package needs to implement history logic

It is not much work at all really. Do you have any preferences regarding how history is handled ? One thing is that you want it to create history by path. How many entries should it keep? Other things you think would be beneficial?

**Comment by idream3** [comment] 2015-08-05 08:39
Hey @christianalfoni thanks for taking the time to understand this :)

Ideally I would like to explicity call a `save()` command when I want to save the current state, then I can add that to an action and append this action to relevant signals.

```javascript
const saveToHistory = function(args, state) {
  const historyIndex = state.save();
  state.push(['historyLabel', historyIndex], args.historyLabel)
}

Controller.signal('somethingHappened', ...actions, saveToHistory);
```

In my example the `save()` returns the history index.

"One thing is that you want it to create history by path" - do you mean that you will need to specify the path you want to save at rather than saving the entire tree? `state.save([path])`

Maybe entries could be configured somewhere? `Controller.setHistory(100)`

Will give this some more thought.

**Comment by christianalfoni** [comment] 2015-08-05 08:43
Aha, I see, this makes sense.

Yes, by path I mean: `state.save(['todos'])`. 

And when you do `state.undo()` it just pops the history stack, right?

Could pass options when instantiating the controller too: `Controller(state, defaultArgs, options)`.

This is actually really cool and very easy to implement, so yeah, lets agree on the API and make it a feature :-)

**Comment by christianalfoni** [comment] 2015-08-05 08:45
Should probably put `state.redo()` inside there as well.

**Comment by christianalfoni** [comment] 2015-08-05 08:53
So to sum up:

```js
// If path is undefined the whole tree will be stored in history
state.save(path); // Save state history to that path
state.undo(path); // Pops the history stack and reverts state, keeps the replaced state for redo
state.redo(path); // Inserts the undone state again
```
I believe redo is also a history array, where a call to save would clear that array. So you can redo multiple times, but should probably not be able to redo when you have changed something again. Hm hm

**Comment by idream3** [comment] 2015-08-05 09:11
Yeah I think these are good ideas! will sleep on it.

Maybe others have some input too...

**Comment by idream3** [comment] 2015-08-05 23:03
Agree that you if you undo and then call `state.save()` it should remove the history items greater than the historyIndex so you can't redo. You probably only need one array.

Nice simple reference here: http://www.macwright.org/2015/05/18/practical-undo.html

Not sure what the API should be though. I think `save()` might be confused with a model save, as in, persisting to a server somewhere - eg. backboneJS behaviour.

```javascript
  // possible API
  state.pushHistory();
  state.saveHistory();
  state.snapshot();
 
  // or prefix with history
  state.history.save()

  // we will need an optional history index to jump to a specific place.
  state.undo(historyIndex);
  state.undo(path, historyIndex);
```

I like your idea of adding options to the Controller. Eg.

```javascript
const options = {
  autoSaveHistory: true, // saves state at the end of every signal?
  maxHistoryStates: 100
}
```

**Comment by christianalfoni** [comment] 2015-08-07 06:07
Hi @idream3 ,

Thanks for the reference!

I agree the `save` might be confusing. I like giving it a domain, as there might be more methods as we move on:

```js
// Just use normal array methods?
state.history.save([path]);
state.history.undo([path]);
state.history.get([path]);
```
With historyIndex, you mean that should work just like doing multiple `undo()`?


Agreed on the options, though `maxHistory` is enough, state is the only history you have :-)

**Comment by idream3** [comment] 2015-08-07 07:53
Re: historyIndex, yeah so say you have 10 history states, user can select say history state 5. Like array, history[5].

**Comment by christianalfoni** [comment] 2015-08-07 08:03
Yeah, but do you think that should remove index [6-9], or should you from history(5) be able to redo history up to [9]? :-) Well, I suppose to answer is an obvious YES, hehe, but do you think there is any reason to be able to finely tune the history? Like "remove history record between 4-6" or "remove history from index 5".

**Comment by idream3** [comment] 2015-08-07 08:30
The way I see it, If you undo to any state and call state.history.save() it will it will remove 6-10 and set the new one at history[6].

Not sure about finer control.

Is there another way we could come at this perhaps... Leave history management up to the user by using state.export/import. Hmm

**Comment by christianalfoni** [comment] 2015-08-10 07:46
Hm hm, good question... I think it depends on the scenario. Like if you work with a text editor it is nice to just undo state changes on a specific state, like `editorValue`.

But if you save something to the server or generelly do async stuff that will not work as you can quickly end up in a race condition, undoing to the wrong state.

But for the first example here it is very easy to build your own undo/redo thingy. Just put the current value into a history array inside the state store and create your own undo/redo signals.

The second is harder to do, but impossible to do generically I think. So yeah... the situation you are in now, what is it exactly? Hehe. Maybe we can try to work on a custom implementation for that scenario and if it is not much work we can deem this "app specific", rather create an example in the documentation on how you can build it.

**Comment by idream3** [comment] 2015-08-10 09:46
Yeah, there are probably many different use cases for history states. 

I would think our implementation is fairly starightforward. I am creating a history panel for a taxonomy editor that records history annotations such as, "node xyz added", "node xyz removed" etc..

The user can select a history item to go back to that specific state in the tree, then redo or either modify that new state.

Saving to the server will be done explicity by the user when they choose, so this will wipe the history state clean, preventing any sync issues.

Hmm, actually this is undecided - if the user wants to undo after a save I guess that is ok. As long as they know that they have to explicitly save again for the changes to persist.

I havn't got my head around saving of the history state yet. Take this simplified example:

```javacsript
const state = State({
  tree: [],
  treeMeta: [],
  editorConfig: {}
});
```

The history would want to keep track of the `tree` and `treeMeta` states but not `editorConfig`. In this case would I call:

```javascript
 state.history.save(['tree']);
  state.history.save(['treeMeta']);
```
?

And then undo them together when needed. (Assume they are both needed for the history and neither can be saved or undo'd independantly).

```javascript
  state.history.undo(['tree'], optionalHistoryIndex); // and
 state.history.undo(['treeMeta'], optionalHistoryIndex);
```

Or save dependant paths together perhaps?
```javascript
 state.history.save(['tree'], ['treeMeta']);

 // then only one undo
 state.history.undo(optionalHistoryIndex);
```

Hmmm. And about the annotations, should this be kept in the tree as a path or be special for the history implementation?

The history array could be something like:
```javascript
 const historyStates = [{
   label: 'History state one',
   data: state
},{
   label: 'History state two',
   data: state
}];
```

**Comment by christianalfoni** [comment] 2015-08-18 07:06
Hi there!

Sorry for late reply, but yeah, busy busy ;-)

In your example I think you would get away with have a history array in the tree.
```js
{
  history: {
    records: [],
    initialStatePath: ['tree'],
    initialState: []
  }
}
```
What you store in the array is the "path", "mutation-type" and "immutable version of the data passed to the mutation". So:

```js
function addTaxonomyStuff (input, state, output) {
  const record = {
    type: 'push',
    path: ['tree'],
    data: input.utils.copyData(input.data)
  };
  state.push('tree', data);
  output({record: record});
}

function addHistory (input, state, output) {
  state.push(['history', 'records'], input.record);
}
```
When you now implement an undo/redo/specific index, you have an action that first changes the "history records". Then you set the initial state of the path, then iterate over the records to reproduce the state.

This is how Cerebral also does it internally and really how "rebuilding state" should work. Not take care of the complete state for each step, but the mutations done to produce a new state. Then you only need to reset the state and replay all state changes up to a certain point. 

Did this make sense? :-)

**Comment by Guria** [comment] 2016-02-27 13:47
Signal remembering now out of scope of cerebral score. Please follow cerebral/cerebral-module-signal-store and cerebral/cerebral-module-recorder as reference module implementations that deals with storing history of signals.

**Closed by Guria** 2016-02-27 13:47 UTC
