### ISSUE TITLE
Exception when missing handler

### ISSUE THREAD

**Issue by rohitlodha** [cerebral/cerebral#127] opened 2015-11-01 11:07 UTC
```javascript   
 action1: function (input, state, output, services) {
                    if(err)
                         output.error({result:err});
                     else {
                         output.success({result:res});
                     }
        }
```
while calling it in signal if error handler is missing and error is thrown in action1, an exception occurs.

```javascript
const signals = {
    sig1: [
        [action1, 
            { 
                   success:[successAction]
            }]
    ]
};
```
if we add error it fixes it.

```javascript
    const signals = {
    sig1: [
        [action1, 
            { 
                   success:[successAction],
                   error:[]
            }]
    ]
};
```

**Comment by christianalfoni** [comment] 2015-11-01 13:07
hi @rohitlodha,

Yes, this is actually by design. If an action outputs an error it is required to handle that error. The reason is that you have created a scenario in your application that needs to be handled some way. If you do not want anything to happen you use an empty array, as you did here. But now you express in your signal that the `action1` actually can output an error, but you do not want anything to happen when that happens :-)

Does that make sense? Let me know if you expect some other behaviour.

**Comment by rohitlodha** [comment] 2015-11-01 13:13
I think we should have a inclusion list, with everything else as ignored. The current methods forces signals to handle all outputs explicitly. I do not understand how this explicit binding helps but it makes edit of one action to directly impact all signals.

**Comment by christianalfoni** [comment] 2015-11-01 13:46
Hi again,

Hm, you do not have to handle all outputs explicitly. You can choose to only run the success output:

```js
 action1: function (input, state, output, services) {
              output.success({result:res});
        }
```

Or you can just run an output:

```js
 action1: function (input, state, output, services) {
              output({result:res});
        }
```

Using just output will make your signal work like this:

```js
const signals = {
    sig1: [
        [action1],
        handleOutputOfAction1
    ]
};
```

Cerebral needs to know what your intention is. With the first example your intention is to handle both and error and a success, so that is why it gives an error. If you do not want to handle `output.error` you should not call it either :-)

Does that solve the scenario? Maybe the documentation is not very clear on this, I really appreciate feedback on things that throw people off, so I can make it more clear :-)

**Comment by rohitlodha** [comment] 2015-11-02 13:28
Thanks for clearing things a bit more. After some more thinking, I see the output handles in a switch case, where we handle specific cases, default handler or skip while you see it as object properties.

I guess I can work with that now and will be back if I see a compelling reason. Thanks for you clarification.

**Comment by christianalfoni** [comment] 2015-12-26 15:40
Closing this for now :-)

**Closed by christianalfoni** 2015-12-26 15:40 UTC
