### ISSUE TITLE
explicit signals connect in view package

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#272] opened 2016-07-14 10:57 UTC
I don't like that we expose all signals to each cerebral connected component.
Also we can't use constants to define signal path.
Here is proposal:
```js
connect({
  foo: 'some.state.path',                // exist
  bar: props => `some.entity.${byKey}`,  // exist
  baz: Computed(),                       // exist
  signals: {                             // proposal
    smthHappened: 'path.to.smthHappened'
  }
}, function Component ({ foo, bar, baz, signals }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => signals.smthHappened()}>
    </div>
  )
})
```
or
```js
connect({
  foo: 'some.state.path',                // exist
  bar: props => `some.entity.${byKey}`,  // exist
  baz: Computed(),                       // exist
}, {                                     // proposal
  smthHappened: 'path.to.smthHappened'
}, function Component ({ foo, bar, baz, smthHappened }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => smthHappened()}>
    </div>
  )
})
```

**Comment by christianalfoni** [comment] 2016-07-14 11:26
We can be explicit about that, but I am not sure that it gives enough value? Like the state paths are used under the hood for optimizations, but the signals does not give more value than just exposing more props... that said, that is not a bad value at all :-)

I personally do not have a specific need for it, but I completely understand why you suggest it :) So if we do this I think we should do the second approach because it is safer... maybe somebody has signals already in their props.

**Comment by garth** [comment] 2016-07-14 11:40
I think that it's a great idea.

It would improve component reusability/testability as you can hook-up different signals and/or functions depending on the scenario.

But I would put them at the top level rather than under signals. The naming convention makes it unlikely that you will have collisions.

**Comment by Guria** [comment] 2016-07-14 12:05
```js
connect({
  foo: 'some.state.path',                     // exist
  foo2: 'state:some.state.path',              // proposal for consistency
  bar: props => `some.entity.${byKey}`,       // exist
  baz: Computed(),                            // exist
  smthHappened: 'signal:path.to.smthHappened' // proposal
}, function Component ({ foo, bar, baz, smthHappened }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => signals.smthHappened()}>
    </div>
  )
})
```

**Comment by christianalfoni** [comment] 2016-07-14 12:13
I think we are taking way too much freedom on that one :) Technically we need to extract signals specifically.. so I still favor:

```js
connect({
  foo: 'some.state.path',                // exist
  bar: props => `some.entity.${byKey}`,  // exist
  baz: Computed(),                       // exist
}, {                                     // proposal
  smthHappened: 'path.to.smthHappened'
}, function Component ({ foo, bar, baz, smthHappened }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => smthHappened()}>
    </div>
  )
})
```
And it reads very well:

1. What state deps has this component
2. What signals does this component use
3. The component

It is also similar to `connect` by Redux:

1. State
2. Actions
3. Component

**Comment by bfitch** [comment] 2016-07-14 13:41
I'll just note that my coworkers were very disturbed by all signals being exposed to every connected component. So, at least I can confirm that "real" users will find value in this.

**Comment by maxfrigge** [comment] 2016-07-14 20:56
And there is always this way.. which breaks the current api but it reads and scales well :)

```javascript
connect({
  state: {
    foo: 'some.state.path',
    bar: props => `some.entity.${byKey}`,
    baz: Computed(),
  },
  signals: {
    smthHappened: 'path.to.smthHappened'
  }
}, function Component ({ foo, bar, baz, smthHappened }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => smthHappened()}>
    </div>
  )
})
```

**Comment by saulshanabrook** [comment] 2016-07-15 02:41
@maxfrigge I like the extra explicitness. Also, if you say don't need any state and just need signals, it's a bit easier to see what is going on in this version (just omit the `state` key).

**Comment by maxfrigge** [comment] 2016-07-15 08:23
Good point @saulshanabrook didn't even see that case.

Another thing: should signals and state be merged when passed as component props or should it be somehow separated e.g. `signals.buttonClicked` to prevent naming conflicts?

**Comment by Guria** [comment] 2016-07-15 10:34
I like `({ foo, bar, baz, smthHappened })` on props more

**Comment by saulshanabrook** [comment] 2016-07-15 15:43
@maxfrigge If we wanted to go all the way with namespacing, we could separate them and encourage nested destructuring. The symmetric structure of this is nice, and it is explicit again. Also, this syntax would allow backwards compatibility with deprecation, until we removed it.

Unless they had an existing key named `state`....

```javascript
connect({
  state: {
    foo: 'some.state.path',
    bar: props => `some.entity.${byKey}`,
    baz: Computed(),
  },
  signals: {
    smthHappened: 'path.to.smthHappened'
  }
}, function Component ({state: {foo, bar, baz}, signals: {smthHappened} }) {
  return (
    <div>
      <li>{foo}</li>
      <li>{bar}</li>
      <li>{baz}</li>
      <button onClick={e => smthHappened()}>
    </div>
  )
})
```

**Comment by maxfrigge** [comment] 2016-07-17 11:03
@saulshanabrook I think it would make things crystal clear, but I am not sure if developers would be bothered by it's additional overhead.

**Comment by christianalfoni** [comment] 2016-07-17 12:55
What is a little bit counter intuitive about the suggestion above is that we are dividing up signals and state at the top, only to "merge" them together again inside the component. 

Also having this magical object on connect that changes its behaviour based on special property keys makes it unnecessarily complex. The object will have 4 modes. Only state, namespace the state with special `state` key, only exposing signals can only be achieved with special `signals` key.... and then having both.

If we say:

connect({
  // this is state
}, {
  // this is signals
}, ...)

There is only one thing to learn about how to grab state and one thing to learn about how to grab signals.

Also the implementation under the hood will be a lot cleaner. Instead of having this extra logic analysing "the mode of the special magical connect object" ;-)

And since we want to bring the props together at the end anyways, we can bring them together for the developer to avoid having nested destructuring.

I have never heard anyone complain about the signature of Redux connect, so they have proven it is a good signature. Why challenge that? :-)

**Comment by maxfrigge** [comment] 2016-07-17 18:15
@christianalfoni I think you make it sound a lot more complicated than it is :)

You pass an object to connect which adds 1:1 to props.

```javascript
connect({
  state: { foo: 'path.foo' },
  signals: {fooClicked: 'path.fooClicked'}
}, (props) => {
  // props = {state: {foo}, signals: {fooClicked}} ... equal structure as above
})
```
You define state and you get `props.state`. 
You define signals and you get `props.signals`.

Not much magic happening here imho :)

It will of course get confusing when allowing multiple variants, which shouldn't be done. I think @saulshanabrook just meant to use it for deprecation.

**Comment by Guria** [comment] 2016-07-17 18:21
I don't like "namespaced"  signals and state. Plain props is much better.

**Comment by christianalfoni** [comment] 2016-07-17 19:53
Hehe, I have a tendency to stretch my opinions as far as I can ;-)

But I still think namespaced is the wrong way to go. When we compare the two approaches there are more negatives on the state/signals namespace approach than extending with a second argument:

**namespace** negatives
- We change current api
- If you write state/signals wrong it will not work
- To support both old and new api we have to create special temporary code that is prone for bugs
- With components that does not use signals we are increasing syntax
- There will never be more than state/signals put into components so it is weird to have only two static properties on an object. Objects are suited for dynamic properties

**extra argument** negatives
- I can not find any negatives? :-)

**Comment by Guria** [comment] 2016-07-18 10:34
prepared a pr to react package: https://github.com/cerebral/cerebral-view-react/pull/64/commits/feb352d1bfac565efb29c9953ecaaea7ba0f90d2

**Comment by Guria** [comment] 2016-07-18 11:03
And I just figured out an issue here.
It will fail with ServerController :(

**Comment by Guria** [comment] 2016-07-18 11:32
Hmm, I think it is safe to return noop functions instead of signals if `controller.isServer === true`

**Comment by Guria** [comment] 2016-07-18 11:33
But maybe we can solve issue with ServerController and Link here to?

**Comment by saulshanabrook** [comment] 2016-07-19 12:36
@christianalfoni you have convinced me, less verbose syntax looks good. It is nice that it is similar to what redux does.

**Comment by Guria** [comment] 2016-07-19 12:51
could anyone test `npm i cerebral/cerebral-view-react#signals-map` with new signature?
should we bring it live?

**Comment by maxfrigge** [comment] 2016-07-19 13:07
I am not quite convinced but I will rest my case.

Tt's always easy to just jump in the redux train :-P

**Comment by edgesoft** [comment] 2016-07-21 16:44
@christianalfoni Like the Redux way.

**Closed** 2016-07-22 20:40 UTC
